package com.cursochat.ws.providersTest;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTest {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
     void test(){
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Il9GWkU0S3Blb090MjNFM2NlZmg1cyJ9.eyJnaXZlbl9uYW1lIjoiTWF0aGV1cyIsImZhbWlseV9uYW1lIjoiRmVycmVpcmEgTGltYSIsIm5pY2tuYW1lIjoibGltYW1hdGhldXMwMDEwIiwibmFtZSI6Ik1hdGhldXMgRmVycmVpcmEgTGltYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJNHAwNXBPMHBrOGdBb0tGdVY4aGg1RTY1ZkJxTkh6ektLbGFNZkNBTHI0TjVybjNVQj1zOTYtYyIsInVwZGF0ZWRfYXQiOiIyMDI2LTAyLTE4VDAzOjEwOjQwLjQ5NloiLCJlbWFpbCI6ImxpbWFtYXRoZXVzMDAxMEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kZXYtd2J2am9wdjY4Yml6cjF3Ny51cy5hdXRoMC5jb20vIiwiYXVkIjoienRZdVZib251TFduR0ZGb0dKV2NGVHQ2MTk4alVUbjYiLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDQ2MDQ1NzE4ODgyMzkxNTg4NyIsImlhdCI6MTc3MTM4NDI0MSwiZXhwIjoxNzcxNDIwMjQxLCJzaWQiOiJIdWpFNTZUTHFqN1ZkWEthTWk3Q0tNMTIxWjFfMEpvVyIsIm5vbmNlIjoiVEhGSVJqRndhVVJZYmtSbE5VaEdaRUYwTm1obGEyVklOMkZMZHpneFFsTklYemRVYkVKaFRrWk5kZz09In0.YMOQ5qcN8VuR-iDR0tO34XcCckYxAUVqK5A2YGC8RGp2ns3FUXdLLnqXmFnVrw9KDKxl91R1rcoQcLvA35y6HXANmg6HC9vqzrpNm5kQvnIh9VNje9h18TXaxdbr6VddzBj3VPISNAdMyWUEl1OcIQdmQwBkN00UuIyyZzvFJaNWS9nNl2OIEShikOyYGRuqtR0eJEwDyj99jyt6MU7tpizoip7C0fsotqnckHsRpUQOgxLTVPsapGvJcONJxJfKIsvHf-1S5ZwKxD5vVdtKdSRTSi67acPtFg4bgsNoDINLzzJgq4uXADUidKe5LArYMChsmy2ZkMEgjyXoDYT5dQ");
        System.out.println(decoded);
    }
}
