server:
  port: ${PORT:8080}

spring:
  redis:
    url: ${REDIS_URL}

  cache:
    type: redis
    redis:
      time-to-live: 600000

  data:
    mongodb:
      uri: ${MONG_DB_URI}
      database: ${MONGODB_DATABASE:chatDb}

app:
  auth:
    jwks-url: ${JWKS_URL}